### Numpy

In [2]:
import numpy as np


creating a numpy aaray

In [3]:
a=np.array([2,5.0,6,4.5])#list
b=np.array([1,2,3,4])#tuple
print(a)
print(b)

[2.  5.  6.  4.5]
[1 2 3 4]


In [ ]:
#tells what kind of python object something is
#eg;list,numpyarray,
#its buil-in python function

type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('float64')

In [ ]:
#data type  of element inside the numpy array
#shows what kind of values are stored(float,int,string etc)
b.dtype

dtype('int64')

In [7]:
#indexing:
print(a[0])
print(a[0:])
print(a[:2])
print(a[1:3])


2.0
[2.  5.  6.  4.5]
[2. 5.]
[5. 6.]


TWO DIMENSIONAL ARRAY:

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8,]])#2rows and 4 column
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#indexing in 2d array:
#syntax:arr[row_index:column_index]
print(b[0,0]) #first row,first column
print(b[1,2])

1
7


In [ ]:
#access entire column:
print(b[:,2])#all rows,third column

[3 7]


In [12]:
print(b[0])

[1 2 3 4]


In [ ]:
print(b[0:])#from zero to all

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b[0:2])#from zero to 2

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
c=np.array([[3,8,-1,0],[4,8,1,1],[2,0,10,4],[1,2,3,4]])
print(c)

[[ 3  8 -1  0]
 [ 4  8  1  1]
 [ 2  0 10  4]
 [ 1  2  3  4]]


In [16]:
#slicing sub array:
print(c[0:2,1:3])

[[ 8 -1]
 [ 8  1]]


In [17]:
print(c[2,0:2])

[2 0]


In [18]:
print(c[1:3,3])

[1 4]


In [19]:
print(c[:,:1])

[[3]
 [4]
 [2]
 [1]]


In [20]:
print(c[1:,2])

[ 1 10  3]


ARRAY INITAILIZATION:

In [ ]:
#creating a array full of zeros
#default d type is float
a=np.zeros((3,4))#3rows and 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
a.dtype

dtype('float64')

In [ ]:
#creating an array full of one 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#specifying dtype
np.zeros((2,2),dtype=int) 

array([[0, 0],
       [0, 0]])

In [26]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
#generate sequence of integers
# syntax:array_names=np.arrange(start,stop,step)
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [30]:
b=np.arange(10,0,-2)
b

array([10,  8,  6,  4,  2])

In [ ]:
#array name=np.full((row,column),default value)
c=np.full((3,3),"a")
c

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [ ]:
d=np.zeros((3,3))
d[[0,1,2],[0,1,2]]=1#after ,its column
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#generate a sequence of equally spaced values between start and end
#syntax:array name=np.linespace(start,stop,no of elements)
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [34]:
d=np.zeros((3,6))
d[[0,1,2],[0,0,0]]=1
d[[0,1,2],[2,2,2]]=3
d[[0,1,2],[4,4,4]]=5
d

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [35]:
s=np.zeros((3,6))
s[:,[0,2,4]]=[1,3,5]
s

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [37]:
k=np.zeros((3,6))
k[[0,1,2],[0,2,4]]=[1,3,5]
k


array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0.]])

In [38]:
s=np.zeros((3,6))
s[[0],[0,2,4]]=1
s[[0],[1,3,5]]=2
s[[1],[0,2,4]]=3
s[[1],[1,3,5]]=4
s[[2],[0,2,4]]=5
s[[2],[1,3,5]]=6
s



array([[1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4.],
       [5., 6., 5., 6., 5., 6.]])

RANDOM MODULE

In [ ]:
#np.random.random()
#numpy- Library 
#random - a submodule dedicated to generating random numbers
#random()-a specific function that generate random values


In [39]:
import numpy as np
arr1=np.random.random()
arr1

0.5169340675890791

In [ ]:
#generate random values btw 0-10
#syntax:array name=np.random.random(no of elements)
import numpy as np
arr1=np.random.random(10)
arr1

array([0.28967079, 0.18815021, 0.76661503, 0.31111814, 0.91874696,
       0.01759698, 0.61153771, 0.11785036, 0.45046482, 0.30360458])

In [41]:
import numpy as np
arr1=np.random.random(5)
arr1

array([0.47682988, 0.58617089, 0.08450539, 0.52162192, 0.98997375])

In [ ]:
#generate 1d arrays of random integers btw start and stop
#syntax:array_name=random.randint(start,stop,no of elemnts)
arr2=np.random.randint(1,10,10)
arr2

array([1, 1, 4, 6, 4, 2, 8, 7, 3, 8], dtype=int32)

In [ ]:
#generate 2d array of random int
#syntax:np.random.randint(start,end(row,column))
arr3=np.random.randint(1,10,(3,3))
arr3

array([[2, 6, 7],
       [6, 1, 3],
       [3, 8, 5]], dtype=int32)

ARRAY ATTRIBUTE:

In [1]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.ndim)# 2 number of dimension
print(arr.shape)#(3,4)rows and column
print(arr.size)# 12 total number of elements
print(arr.dtype)# int 64 data type
print(arr.itemsize)#8 bytes per elemnt
print(arr.nbytes)# 96 total memory=size * itemsize

2
(3, 4)
12
int64
8
96


In [3]:
#THREE DIMENSIONAL ARRAY:
arr3d=np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3d.shape #2 depth(block),2rows,2 column

(2, 2, 2)

In [6]:
#example:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
a.shape

(6,)

In [ ]:
a.ndim#dimension

1

In [9]:
a.dtype

dtype('int64')

CHANGING TYPE OF ARRAY:

In [10]:
#astype
a=a.astype('float')
a

array([0., 1., 2., 3., 4., 5.])

In [11]:
a.dtype

dtype('float64')

ADD/REMOVING ELEMENTS:

In [ ]:
arr=np.array([2,20,7,8])
np.append(arr,6)# add 6 to the last

array([ 2, 20,  7,  8,  6])

In [ ]:
arr3=np.random.randint(1,10,(3,3))
arr3 # get random numbers from 1 to 10

array([[7, 4, 2],
       [2, 1, 3],
       [7, 2, 8]], dtype=int32)

In [ ]:
np.append(arr3,22)# will add 22 to last while making it 1 D

array([ 7,  4,  2,  2,  1,  3,  7,  2,  8, 22])

In [ ]:
#insert an elemnt in aperticular position
#np.insert(array name,position,element)

np.insert(arr,2,8)

array([ 2, 20,  8,  7,  8])

In [ ]:
#np.insert(array name,position,value,axis=0/1)
#axis0=row
#axis1=column
np.insert(arr3,2,3,axis=0)

array([[7, 4, 2],
       [2, 1, 3],
       [3, 3, 3],
       [7, 2, 8]], dtype=int32)

In [ ]:
np.insert(arr3,0,[2,3,4],axis=0)# inserting in row

array([[2, 3, 4],
       [7, 4, 2],
       [2, 1, 3],
       [7, 2, 8]], dtype=int32)

In [21]:
np.insert(arr3,2,[1,1,1],axis=0)

array([[7, 4, 2],
       [2, 1, 3],
       [1, 1, 1],
       [7, 2, 8]], dtype=int32)

In [22]:
np.insert(arr3,2,3,axis=1)

array([[7, 4, 3, 2],
       [2, 1, 3, 3],
       [7, 2, 3, 8]], dtype=int32)

In [24]:
arr4=np.random.randint(1,10,(3,4))
arr4

array([[3, 4, 3, 6],
       [8, 6, 6, 4],
       [3, 4, 1, 8]], dtype=int32)

In [25]:
#delete an elemnt ,row or column deletion
#np.delete(array name,position)
s=np.delete(arr4,3)
s

array([3, 4, 3, 8, 6, 6, 4, 3, 4, 1, 8], dtype=int32)

In [26]:
s=np.delete(arr4,7)
s

array([3, 4, 3, 6, 8, 6, 6, 3, 4, 1, 8], dtype=int32)

In [27]:
#np.delete(arrayname,positon,row/column)
np.delete(arr4,1,axis=1)

array([[3, 3, 6],
       [8, 6, 4],
       [3, 1, 8]], dtype=int32)

In [28]:
np.delete(arr4,2,axis=0)

array([[3, 4, 3, 6],
       [8, 6, 6, 4]], dtype=int32)

In [29]:
np.delete(arr4,(0,1),axis=1)
#delete column 0 and column 1from the array

array([[3, 6],
       [6, 4],
       [1, 8]], dtype=int32)

In [30]:
np.delete(arr4,(0,1,2),axis=0)

array([], shape=(0, 4), dtype=int32)

In [31]:
#creating copy of a array:
a=np.array([2,3,4,5])
b=np.copy(a)
b

array([2, 3, 4, 5])

In [33]:
#another method to copy:
b=a.copy()
b

array([2, 3, 4, 5])

SORTING:

In [34]:
a=[4,5,2,7,8]
np.sort(a)

array([2, 4, 5, 7, 8])

In [ ]:
np.sort(a)[::-1] # sort in descending 

array([8, 7, 5, 4, 2])

In [36]:
a.sort()
a

[2, 4, 5, 7, 8]

In [37]:
c=np.array([[3,2,3],[5,3,8],[5,3,0]])
c

array([[3, 2, 3],
       [5, 3, 8],
       [5, 3, 0]])

In [ ]:
np.sort(c) #sort in ascending

array([[2, 3, 3],
       [3, 5, 8],
       [0, 3, 5]])

In [40]:
np.sort(c)[::-1]

array([[0, 3, 5],
       [3, 5, 8],
       [2, 3, 3]])

In [41]:
c

array([[3, 2, 3],
       [5, 3, 8],
       [5, 3, 0]])

In [42]:
-c

array([[-3, -2, -3],
       [-5, -3, -8],
       [-5, -3,  0]])

In [43]:
np.sort(-c)

array([[-3, -3, -2],
       [-8, -5, -3],
       [-5, -3,  0]])

In [44]:
-np.sort(-c)

array([[3, 3, 2],
       [8, 5, 3],
       [5, 3, 0]])

In [45]:
-c
np.sort(-c)
-np.sort(-c)

array([[3, 3, 2],
       [8, 5, 3],
       [5, 3, 0]])

In [46]:
import numpy as np
arr=np.array([[12,5,7],[1,3,9],[8,2,6]])
print(arr)
s_arr=np.sort(arr,axis=1)
print(s_arr)
#axis 0=column(vertical)
#axis 1=row(horizonatl)

[[12  5  7]
 [ 1  3  9]
 [ 8  2  6]]
[[ 5  7 12]
 [ 1  3  9]
 [ 2  6  8]]


In [4]:
import numpy as np
arr1=np.random.randint(2,8,(3,3))
arr2=np.random.randint(0,5,(3,3))
arr3=np.random.randint(3,9,(3,3))
print(arr1)
print(arr2)
print(arr3)

[[6 6 2]
 [7 5 6]
 [4 5 4]]
[[0 4 2]
 [2 3 1]
 [2 4 3]]
[[5 6 4]
 [7 7 5]
 [4 4 5]]


In [ ]:
np.vstack([arr1,arr2,arr3])#verical stack

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4],
       [0, 4, 2],
       [2, 3, 1],
       [2, 4, 3],
       [5, 6, 4],
       [7, 7, 5],
       [4, 4, 5]], dtype=int32)

In [6]:
np.concatenate([arr1,arr2],axis=0)#same as v stack

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4],
       [0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [7]:
np.hstack([arr1,arr2])

array([[6, 6, 2, 0, 4, 2],
       [7, 5, 6, 2, 3, 1],
       [4, 5, 4, 2, 4, 3]], dtype=int32)

In [8]:
np.concatenate([arr1,arr2],axis=1)#same as hstack

array([[6, 6, 2, 0, 4, 2],
       [7, 5, 6, 2, 3, 1],
       [4, 5, 4, 2, 4, 3]], dtype=int32)

In [9]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [ ]:
arr1.ravel()#convert multidimnsional array into 1D

array([6, 6, 2, 7, 5, 6, 4, 5, 4], dtype=int32)

In [12]:
arr3

array([[5, 6, 4],
       [7, 7, 5],
       [4, 4, 5]], dtype=int32)

In [14]:
arr3[1,2]#accesing a particular elemnt ,1row,2nd column (zero index)

np.int32(5)

In [15]:
arr3[0::2,0:1]
#arr[row,column]
#arr[start:stop:step,start:stop:step]

array([[5],
       [4]], dtype=int32)

In [16]:
arr=np.array([[3,2,-1,4],[8,7,0,1],[2,6,3,-5],[4,8,7,2]])
arr

array([[ 3,  2, -1,  4],
       [ 8,  7,  0,  1],
       [ 2,  6,  3, -5],
       [ 4,  8,  7,  2]])

In [17]:
arr[1:3:,1::2]

array([[ 7,  1],
       [ 6, -5]])

In [18]:
arr[1::2,0:2:]

array([[8, 7],
       [4, 8]])

In [ ]:
#access elemnt diagonally
arr=np.array([[3,2,-1,4],[8,7,0,1],[2,6,3,-5],[4,8,7,2]])
arr

array([[ 3,  2, -1,  4],
       [ 8,  7,  0,  1],
       [ 2,  6,  3, -5],
       [ 4,  8,  7,  2]])

In [21]:
b=arr.diagonal()
b

array([3, 7, 3, 2])

In [30]:
ar=np.zeros((8,8))
ar

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
ar[::2,::2]=1
print(ar)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
ar[1::2,1::2]=1
print(ar)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


ARRAY ARITHEMETIC OPERATION:

In [33]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [34]:
arr2

array([[0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [ ]:
arr1*arr2 #element wise multiplication

array([[ 0, 24,  4],
       [14, 15,  6],
       [ 8, 20, 12]], dtype=int32)

In [36]:
np.matmul(arr1,arr2)#matrix multiplication

array([[16, 50, 24],
       [22, 67, 37],
       [18, 47, 25]], dtype=int32)

In [38]:
a=np.ones((2,3))
b=np.full((3,2),5)
c=np.full((2,3),5)
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[5 5 5]
 [5 5 5]]


In [39]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [40]:
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [41]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [42]:
np.max(arr1)

np.int32(7)

In [43]:
np.min(arr1)

np.int32(2)

In [44]:
np.max(arr1,axis=0)#column 

array([7, 6, 6], dtype=int32)

In [47]:
np.min(arr1,axis=0)

array([4, 5, 2], dtype=int32)

In [48]:
np.max(arr1,axis=1)#row

array([6, 7, 5], dtype=int32)

In [49]:
np.min(arr1,axis=1)

array([2, 5, 4], dtype=int32)

In [50]:
np.sum(arr1)

np.int64(45)

In [51]:
np.sum([arr1,arr2])

np.int64(66)

In [52]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [53]:
arr2

array([[0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [54]:
np.sum([arr1,arr2],axis=0)#column wisw adds

array([[ 6, 10,  4],
       [ 9,  8,  7],
       [ 6,  9,  7]])

BOOLEAN INDEXING:

In [ ]:
import numpy as np
data=np.array([15,-3,42,-8,27,-1,55,0,18])
#step1:create boolean mask
mask=data>0
print(mask)#true will be given to positve number and false for negative

[ True False  True False  True False  True False  True]


In [2]:
#step2:use mask to filter
print(data[mask])#only positive values 
#short hand (most common way)
print(data[data>0])#greater than zero will print
print(data[data<0])#will print negativ numbers 
print(data[data==0])#numbers =0

#multiple conditions- use &(and),|(or),~(not)
print(data[(data>0) &(data<30)])
print(data[(data<0)|(data>40)])

#replace value that meet a condition:
data[data <0]=0# set all negative values as zero 
print(data)
#np.where-choose values based on condition
result=np.where(data>20,'high','low')#if the data is greater than 20 will print high otherwise low
print(result)

[15 42 27 55 18]
[15 42 27 55 18]
[-3 -8 -1]
[0]
[15 27 18]
[-3 42 -8 -1 55]
[15  0 42  0 27  0 55  0 18]
['low' 'low' 'high' 'low' 'high' 'low' 'high' 'low' 'low']


ARRAY RESHAPING:

In [3]:
arr=np.arange(1,13)#create 12 elements
print(arr.shape) # return the size of the array
m=arr.reshape(3,4)#reshape into 3 rows and 4 columns
print(m)

#use -1 tp let numpy calculate one diamension automatically
m2=arr.reshape(4,-1)#4rows, numpy will figure out the column =3
m3=arr.reshape(-1,6)#rows =2 will figure out by numpy,6column

#reshape to 3D:
t=arr.reshape(2,2,3)#2block,2row,3column
print(t.shape)

#resize -modifies array in place(can change total size)
new_arr=np.resize(arr,(2,5))
print(new_arr)#fills with zero if bigger 

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(2, 2, 3)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
m=np.array([[1,2,3],[4,5,6]])

#flatten()-always return a copy
flat=m.flatten()
print(flat)
flat[0]=999# doesnot change in original m 
print(flat)
print(m)

[1 2 3 4 5 6]
[999   2   3   4   5   6]
[[1 2 3]
 [4 5 6]]


In [5]:
m=np.array([[1,2,3],[4,5,6]])

#ravel()-return a view if positive
rav=m.ravel()
print(rav)
rav[0]=999#changes in orinal m 
#order='C'=row-major(default)(elements are sorted row by row )'F'=column
print(m.flatten(order='F'))

[1 2 3 4 5 6]
[999   4   2   5   3   6]


TRANSPOSE

In [6]:
m=np.array([[1,2,3],
            [4,5,6]])#(2,3)
print(m.shape)

#2 ways to transpose
t1=m.T #attribute
t2=m.transpose()#function method
print(t1)
print(t2)
print(t1.shape)#(3,2) rows and columns are swapped


(2, 3)
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


SPLITTING ARRRY:


In [7]:
arr=np.arange(12).reshape(3,4)
print(arr)
 
#hsplit=split horizontally(column wise)
left,right=np.hsplit(arr,2)#split into 2 equal parts
print(left)#print col 0,1 lefwise
print(right)#print col 2,3 right wise


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [8]:
#vsplit- vertical split(row wise)
top,bottom=np.vsplit(arr,[1])#split after row 1
print(top)
print(bottom)



[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
#split=generic(axis=0 for rows ,1=column)
parts=np.split(arr,[1,3],axis=0)#split at row 1 and 3
#parts[0]=row 0,parts[1]=rows1-2,parts[2]=empty
print(parts)

#array split- aloows unequal split 
part=np.array_split(np.arange(10),3)
print(part)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([], shape=(0, 4), dtype=int32)]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


ELEMENT WISE ARITHEMETIC

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])

#arithemetic oprtn elemnt by elemnt:
print(a+b)#(10+1,20+2,30+3,40+4,50+5)
print(a-b)
print(a*b)
print(a/b)
print(a**b)#squaring each elemnt
print(b%a)#modulo
print(b // a)#floor division

#scalar operations (applied to every elemnt)
print(a+100)#[101,102,103,104,105]
print(a*3)
print(a>3)#[false,false,false,true,true]#if a have elemnts greter than 3 will come true


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[          1     1048576 -1010140999           0  1296002393]
[0 0 0 0 0]
[10 10 10 10 10]
[101 102 103 104 105]
[ 3  6  9 12 15]
[False False False  True  True]


UNIVERSAL FUNCTION


In [12]:
arr=np.array([1.0,4.0,9.0,16.0,25.0])

#math u function:
a=np.sqrt(arr)#square root 
print(a)

b=np.square(arr)#square of the elemnt
print(b)

c=np.abs(np.array([-1,-2,3]))
print(c)

d=np.log(arr) #natural log(ln)
print(d)

e=np.log2(arr)#log base
print(e)
 
f=np.log10(arr)#log base(10)
print(f)

g=np.exp(np.array([1,2,3]))#exponential
print(g)


#TRIGNOMETRIC UFUNCTION:
angles=np.array([0,np.pi/6,np.pi/4,np.pi/2,np.pi])
h=np.sin(angles)
print(h)


i=np.cos(angles)
print(i)

j=np.tan(angles)
print(j)

k=np.degrees(angles) # convert radians into degrees
print(k)

l=np.radians(np.array([0,30,45,90,100]))#degrees to radians
print(l)


#ROUNDING:
x=np.array([1,23,2.56,3.78,4.51])
print(x)

m=np.round(x,1)#(1.,2.6,3.8,4.5)
print(m)

n=np.floor(x)#[1.,2.,3.,4.,5.]3round down
print(n)

o=np.ceil(x)#round up[2.,3.,4.,]
print(o)

p=np.trunc(x)#drop decimal part
print(p)

[1. 2. 3. 4. 5.]
[  1.  16.  81. 256. 625.]
[1 2 3]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[0.         2.         3.169925   4.         4.64385619]
[0.         0.60205999 0.95424251 1.20411998 1.39794001]
[ 2.71828183  7.3890561  20.08553692]
[0.00000000e+00 5.00000000e-01 7.07106781e-01 1.00000000e+00
 1.22464680e-16]
[ 1.00000000e+00  8.66025404e-01  7.07106781e-01  6.12323400e-17
 -1.00000000e+00]
[ 0.00000000e+00  5.77350269e-01  1.00000000e+00  1.63312394e+16
 -1.22464680e-16]
[  0.  30.  45.  90. 180.]
[0.         0.52359878 0.78539816 1.57079633 1.74532925]
[ 1.   23.    2.56  3.78  4.51]
[ 1.  23.   2.6  3.8  4.5]
[ 1. 23.  2.  3.  4.]
[ 1. 23.  3.  4.  5.]
[ 1. 23.  2.  3.  4.]


AGGREGATE FUNCTION:

In [13]:
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

#whole array
print(np.sum(m))#sum of all
print(np.mean(m))
print(np.min(m))
print(np.max(m))
print(np.prod(m))#product of all
print(np.std(m))#standard deviation
print(np.var(m))#variance

#along an axis:
print(np.sum(m,axis=0))#axis 0=column,sum of each column 
print(np.sum(m,axis=1))#sum of each column
print(np.mean(m,axis=0))#mean of each column
print(np.max(m,axis=1))#max of rach row 

#cumulative:
print(np.cumsum(m,axis=1))#running total accros each row
#[1 3 6]
#[4 9 15]
#[7,15,24]


#index of min/max
print(np.argmin(m))#-0-flat index of minimum
print(np.argmax(m))#8-flat index of maximum
print(np.argmax(m,axis=0))#[2 2 2], row index of max in each column


45
5.0
1
9
362880
2.581988897471611
6.666666666666667
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[3 6 9]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
0
8
[2 2 2]


BROADCASTING:

In [14]:
#scholar broadcast- simplest case
arr=np.array([1,2,3,4])
print(arr+10)#[11 12 13 14]

#1D+2D broadcasting:
matrix=np.array([[1,2,3],
                 [4,5,6]])
row=np.array([10,20,30])
print(matrix+row)
#[11 22 33] -row is added to Each of matrix
#[14 25 36]

#column vactor broadcast:
col=np.array([[100],
              [200]])
print(matrix+col)
#[[101 102 103]
#[204 205 206]]

#practical:normalise each column (subtract column mean)
col_means=matrix.mean(axis=0)
print(col_means)
normalised=matrix-col_means # broadcast:(2,3)-(3)=(2,3)
#[[-1.5 -1.5 -1.5]
#[1.5 1.5 1.5]

[11 12 13 14]
[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]
[2.5 3.5 4.5]


STATSTICAL FUNCTION

descriptive statistics:

In [1]:
import numpy as np
data=np.array([23,45,12,67,34,89,56,23,78,45,34,56])
print('count: ', data.size)
print('sum: ',np.sum(data))
print('mean: ',np.mean(data))
print('medain: ',np.median(data))
print('std dev: ',np.std(data,ddof=1))
print('variance:',np.var(data,ddof=1))# delta degree of freedom .[1=population(full elemnts),0=sample]
print('min: ',np.min(data))
print('max: ',np.max(data))

count:  12
sum:  562
mean:  46.833333333333336
medain:  45.0
std dev:  23.373774477677614
variance: 546.3333333333334
min:  12
max:  89


PERCENTILE AND QUANTILE:

In [2]:
data=np.array([10,20,25,30,35,40,50,60,70,80,90,100])
#percentile=-percentage of data below that value
print(np.percentile(data, 25)) #q1=30(quartile)
print(np.percentile(data,50))#q2=medain=45.0
print(np.percentile(data,75))#q3
print(np.percentile(data,[0,25,50,75,100]))#all quartiles at once

#quantile-same but uses 0-1 scale instead of 1-100
print(np.percentile(data,0.25))#q1
print(np.percentile(data,[0,.25,.5,.75,.1]))#s number summery

#IQR-(interquartile range)-measure of spread
q1=np.percentile(data,25)
q2=np.percentile(data,75)
iqr=q1-q2
print(f'IQR:{iqr}')#42.5

28.75
45.0
72.5
[ 10.    28.75  45.    72.5  100.  ]
10.275
[10.    10.275 10.55  10.825 10.11 ]
IQR:-43.75


QUESTIONS:

In [ ]:
#1.numpy program to create matrix3*3ranging from 2-10
import numpy as np
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [11]:
#prgrm to get unique number of a array:
array=[1,2,3,4,5,6,3,2,4,5,8,9,11]
np.unique(array)#unique()=(remove therepeated elements)



array([ 1,  2,  3,  4,  5,  6,  8,  9, 11])

In [15]:
#union of 2 array:
array1=[2,4,6,8,10]
array2=[1,3,5,7,9]
np.union1d(array1,array2)#union1d()=return the unique elemnts in sorted order

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
#createa 2 diamensional array of size2*3 (4byte integr elmnt)print size,type,datatype
array=np.array([[1,2,3],[5,6,7]],dtype=np.int32)
print("shape:",array.shape)
print("type:",type(array))
print("data type:",array.dtype)
print("itemsize:",array.itemsize,"bytes")

shape: (2, 3)
type: <class 'numpy.ndarray'>
data type: int32
itemsize: 4 bytes


In [ ]:
#2d array diagonals=[4,5,6,8]nd 0 else everwhere
diagonal_values=[4,5,6,8]
diagonal_array=np.diag(diagonal_values)#np.diag()willcreate array in 2dand diagnoal given and zeros else evrywhere
print(diagonal_array)


[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [ ]:
#create a null vector size6(1d)update 6th value to 9
null_vector=np.zeros(6)
print("before:",null_vector)
null_vector[5]=9
print("after:",null_vector)

before: [0. 0. 0. 0. 0. 0.]
after: [0. 0. 0. 0. 0. 9.]


In [ ]:
#array with values ranging from 12-39 and also its length
bn=np.arange(12,40)
print("length:",len(bn))
print(bn)

length: 28
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39]


In [77]:
#reverse 1d array

array=np.array([3,8,0,9,7,61,3,12])
print("original:",array)
#method1=slicing:
reversed_1=array[::-1]
print("Reversed(slicing):",reversed_1)
#method2:
np.flip(array)
reversed_2=np.flip(array)
print("Reversed(np.flip):",reversed_2)



original: [ 3  8  0  9  7 61  3 12]
Reversed(slicing): [12  3 61  7  9  0  8  3]
Reversed(np.flip): [12  3 61  7  9  0  8  3]


In [87]:
#checkerboardpattern
checkerboard=np.zeros((8,8))
checkerboard[::2,::2]=1
checkerboard[1::2,1::2]=1
print(checkerboard.astype(int))

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
