# Numpy

## Numpy

### Numpy

In [2]:
import numpy as np


creating a numpy aaray

In [3]:
a=np.array([2,5.0,6,4.5])#list
b=np.array([1,2,3,4])#tuple
print(a)
print(b)

[2.  5.  6.  4.5]
[1 2 3 4]


In [ ]:
#tells what kind of python object something is
#eg;list,numpyarray,
#its buil-in python function

type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('float64')

In [ ]:
#data type  of element inside the numpy array
#shows what kind of values are stored(float,int,string etc)
b.dtype

dtype('int64')

In [7]:
#indexing:
print(a[0])
print(a[0:])
print(a[:2])
print(a[1:3])


2.0
[2.  5.  6.  4.5]
[2. 5.]
[5. 6.]


TWO DIMENSIONAL ARRAY:

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8,]])#2rows and 4 column
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#indexing in 2d array:
#syntax:arr[row_index:column_index]
print(b[0,0]) #first row,first column
print(b[1,2])

1
7


In [ ]:
#access entire column:
print(b[:,2])#all rows,third column

[3 7]


In [12]:
print(b[0])

[1 2 3 4]


In [ ]:
print(b[0:])#from zero to all

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b[0:2])#from zero to 2

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
c=np.array([[3,8,-1,0],[4,8,1,1],[2,0,10,4],[1,2,3,4]])
print(c)

[[ 3  8 -1  0]
 [ 4  8  1  1]
 [ 2  0 10  4]
 [ 1  2  3  4]]


In [16]:
#slicing sub array:
print(c[0:2,1:3])

[[ 8 -1]
 [ 8  1]]


In [17]:
print(c[2,0:2])

[2 0]


In [18]:
print(c[1:3,3])

[1 4]


In [19]:
print(c[:,:1])

[[3]
 [4]
 [2]
 [1]]


In [20]:
print(c[1:,2])

[ 1 10  3]


ARRAY INITAILIZATION:

In [ ]:
#creating a array full of zeros
#default d type is float
a=np.zeros((3,4))#3rows and 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
a.dtype

dtype('float64')

In [ ]:
#creating an array full of one 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#specifying dtype
np.zeros((2,2),dtype=int) 

array([[0, 0],
       [0, 0]])

In [26]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
#generate sequence of integers
# syntax:array_names=np.arrange(start,stop,step)
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [30]:
b=np.arange(10,0,-2)
b

array([10,  8,  6,  4,  2])

In [ ]:
#array name=np.full((row,column),default value)
c=np.full((3,3),"a")
c

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [ ]:
d=np.zeros((3,3))
d[[0,1,2],[0,1,2]]=1#after ,its column
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#generate a sequence of equally spaced values between start and end
#syntax:array name=np.linespace(start,stop,no of elements)
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [34]:
d=np.zeros((3,6))
d[[0,1,2],[0,0,0]]=1
d[[0,1,2],[2,2,2]]=3
d[[0,1,2],[4,4,4]]=5
d

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [35]:
s=np.zeros((3,6))
s[:,[0,2,4]]=[1,3,5]
s

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [37]:
k=np.zeros((3,6))
k[[0,1,2],[0,2,4]]=[1,3,5]
k


array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0.]])

In [38]:
s=np.zeros((3,6))
s[[0],[0,2,4]]=1
s[[0],[1,3,5]]=2
s[[1],[0,2,4]]=3
s[[1],[1,3,5]]=4
s[[2],[0,2,4]]=5
s[[2],[1,3,5]]=6
s



array([[1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4.],
       [5., 6., 5., 6., 5., 6.]])

RANDOM MODULE

In [ ]:
#np.random.random()
#numpy- Library 
#random - a submodule dedicated to generating random numbers
#random()-a specific function that generate random values


In [39]:
import numpy as np
arr1=np.random.random()
arr1

0.5169340675890791

In [ ]:
#generate random values btw 0-10
#syntax:array name=np.random.random(no of elements)
import numpy as np
arr1=np.random.random(10)
arr1

array([0.28967079, 0.18815021, 0.76661503, 0.31111814, 0.91874696,
       0.01759698, 0.61153771, 0.11785036, 0.45046482, 0.30360458])

In [41]:
import numpy as np
arr1=np.random.random(5)
arr1

array([0.47682988, 0.58617089, 0.08450539, 0.52162192, 0.98997375])

In [ ]:
#generate 1d arrays of random integers btw start and stop
#syntax:array_name=random.randint(start,stop,no of elemnts)
arr2=np.random.randint(1,10,10)
arr2

array([1, 1, 4, 6, 4, 2, 8, 7, 3, 8], dtype=int32)

In [ ]:
#generate 2d array of random int
#syntax:np.random.randint(start,end(row,column))
arr3=np.random.randint(1,10,(3,3))
arr3

array([[2, 6, 7],
       [6, 1, 3],
       [3, 8, 5]], dtype=int32)