# Numpy

## Numpy

### Numpy

In [2]:
import numpy as np


creating a numpy aaray

In [3]:
a=np.array([2,5.0,6,4.5])#list
b=np.array([1,2,3,4])#tuple
print(a)
print(b)

[2.  5.  6.  4.5]
[1 2 3 4]


In [ ]:
#tells what kind of python object something is
#eg;list,numpyarray,
#its buil-in python function

type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('float64')

In [ ]:
#data type  of element inside the numpy array
#shows what kind of values are stored(float,int,string etc)
b.dtype

dtype('int64')

In [7]:
#indexing:
print(a[0])
print(a[0:])
print(a[:2])
print(a[1:3])


2.0
[2.  5.  6.  4.5]
[2. 5.]
[5. 6.]


TWO DIMENSIONAL ARRAY:

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8,]])#2rows and 4 column
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#indexing in 2d array:
#syntax:arr[row_index:column_index]
print(b[0,0]) #first row,first column
print(b[1,2])

1
7


In [ ]:
#access entire column:
print(b[:,2])#all rows,third column

[3 7]


In [12]:
print(b[0])

[1 2 3 4]


In [ ]:
print(b[0:])#from zero to all

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b[0:2])#from zero to 2

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
c=np.array([[3,8,-1,0],[4,8,1,1],[2,0,10,4],[1,2,3,4]])
print(c)

[[ 3  8 -1  0]
 [ 4  8  1  1]
 [ 2  0 10  4]
 [ 1  2  3  4]]


In [16]:
#slicing sub array:
print(c[0:2,1:3])

[[ 8 -1]
 [ 8  1]]


In [17]:
print(c[2,0:2])

[2 0]


In [18]:
print(c[1:3,3])

[1 4]


In [19]:
print(c[:,:1])

[[3]
 [4]
 [2]
 [1]]


In [20]:
print(c[1:,2])

[ 1 10  3]


ARRAY INITAILIZATION:

In [ ]:
#creating a array full of zeros
#default d type is float
a=np.zeros((3,4))#3rows and 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
a.dtype

dtype('float64')

In [ ]:
#creating an array full of one 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#specifying dtype
np.zeros((2,2),dtype=int) 

array([[0, 0],
       [0, 0]])

In [26]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [29]:
#generate sequence of integers
# syntax:array_names=np.arrange(start,stop,step)
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [30]:
b=np.arange(10,0,-2)
b

array([10,  8,  6,  4,  2])

In [ ]:
#array name=np.full((row,column),default value)
c=np.full((3,3),"a")
c

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

In [ ]:
d=np.zeros((3,3))
d[[0,1,2],[0,1,2]]=1#after ,its column
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#generate a sequence of equally spaced values between start and end
#syntax:array name=np.linespace(start,stop,no of elements)
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [34]:
d=np.zeros((3,6))
d[[0,1,2],[0,0,0]]=1
d[[0,1,2],[2,2,2]]=3
d[[0,1,2],[4,4,4]]=5
d

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [35]:
s=np.zeros((3,6))
s[:,[0,2,4]]=[1,3,5]
s

array([[1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.],
       [1., 0., 3., 0., 5., 0.]])

In [37]:
k=np.zeros((3,6))
k[[0,1,2],[0,2,4]]=[1,3,5]
k


array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0.]])

In [38]:
s=np.zeros((3,6))
s[[0],[0,2,4]]=1
s[[0],[1,3,5]]=2
s[[1],[0,2,4]]=3
s[[1],[1,3,5]]=4
s[[2],[0,2,4]]=5
s[[2],[1,3,5]]=6
s



array([[1., 2., 1., 2., 1., 2.],
       [3., 4., 3., 4., 3., 4.],
       [5., 6., 5., 6., 5., 6.]])

RANDOM MODULE

In [ ]:
#np.random.random()
#numpy- Library 
#random - a submodule dedicated to generating random numbers
#random()-a specific function that generate random values


In [39]:
import numpy as np
arr1=np.random.random()
arr1

0.5169340675890791

In [ ]:
#generate random values btw 0-10
#syntax:array name=np.random.random(no of elements)
import numpy as np
arr1=np.random.random(10)
arr1

array([0.28967079, 0.18815021, 0.76661503, 0.31111814, 0.91874696,
       0.01759698, 0.61153771, 0.11785036, 0.45046482, 0.30360458])

In [41]:
import numpy as np
arr1=np.random.random(5)
arr1

array([0.47682988, 0.58617089, 0.08450539, 0.52162192, 0.98997375])

In [ ]:
#generate 1d arrays of random integers btw start and stop
#syntax:array_name=random.randint(start,stop,no of elemnts)
arr2=np.random.randint(1,10,10)
arr2

array([1, 1, 4, 6, 4, 2, 8, 7, 3, 8], dtype=int32)

In [ ]:
#generate 2d array of random int
#syntax:np.random.randint(start,end(row,column))
arr3=np.random.randint(1,10,(3,3))
arr3

array([[2, 6, 7],
       [6, 1, 3],
       [3, 8, 5]], dtype=int32)

ARRAY ATTRIBUTE:

In [1]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.ndim)# 2 number of dimension
print(arr.shape)#(3,4)rows and column
print(arr.size)# 12 total number of elements
print(arr.dtype)# int 64 data type
print(arr.itemsize)#8 bytes per elemnt
print(arr.nbytes)# 96 total memory=size * itemsize

2
(3, 4)
12
int64
8
96


In [3]:
#THREE DIMENSIONAL ARRAY:
arr3d=np.array([[[1,2],[3,4]],
               [[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3d.shape #2 depth(block),2rows,2 column

(2, 2, 2)

In [6]:
#example:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
a.shape

(6,)

In [ ]:
a.ndim#dimension

1

In [9]:
a.dtype

dtype('int64')

CHANGING TYPE OF ARRAY:

In [10]:
#astype
a=a.astype('float')
a

array([0., 1., 2., 3., 4., 5.])

In [11]:
a.dtype

dtype('float64')

ADD/REMOVING ELEMENTS:

In [ ]:
arr=np.array([2,20,7,8])
np.append(arr,6)# add 6 to the last

array([ 2, 20,  7,  8,  6])

In [ ]:
arr3=np.random.randint(1,10,(3,3))
arr3 # get random numbers from 1 to 10

array([[7, 4, 2],
       [2, 1, 3],
       [7, 2, 8]], dtype=int32)

In [ ]:
np.append(arr3,22)# will add 22 to last while making it 1 D

array([ 7,  4,  2,  2,  1,  3,  7,  2,  8, 22])

In [ ]:
#insert an elemnt in aperticular position
#np.insert(array name,position,element)

np.insert(arr,2,8)

array([ 2, 20,  8,  7,  8])

In [ ]:
#np.insert(array name,position,value,axis=0/1)
#axis0=row
#axis1=column
np.insert(arr3,2,3,axis=0)

array([[7, 4, 2],
       [2, 1, 3],
       [3, 3, 3],
       [7, 2, 8]], dtype=int32)

In [ ]:
np.insert(arr3,0,[2,3,4],axis=0)# inserting in row

array([[2, 3, 4],
       [7, 4, 2],
       [2, 1, 3],
       [7, 2, 8]], dtype=int32)

In [21]:
np.insert(arr3,2,[1,1,1],axis=0)

array([[7, 4, 2],
       [2, 1, 3],
       [1, 1, 1],
       [7, 2, 8]], dtype=int32)

In [22]:
np.insert(arr3,2,3,axis=1)

array([[7, 4, 3, 2],
       [2, 1, 3, 3],
       [7, 2, 3, 8]], dtype=int32)

In [24]:
arr4=np.random.randint(1,10,(3,4))
arr4

array([[3, 4, 3, 6],
       [8, 6, 6, 4],
       [3, 4, 1, 8]], dtype=int32)

In [25]:
#delete an elemnt ,row or column deletion
#np.delete(array name,position)
s=np.delete(arr4,3)
s

array([3, 4, 3, 8, 6, 6, 4, 3, 4, 1, 8], dtype=int32)

In [26]:
s=np.delete(arr4,7)
s

array([3, 4, 3, 6, 8, 6, 6, 3, 4, 1, 8], dtype=int32)

In [27]:
#np.delete(arrayname,positon,row/column)
np.delete(arr4,1,axis=1)

array([[3, 3, 6],
       [8, 6, 4],
       [3, 1, 8]], dtype=int32)

In [28]:
np.delete(arr4,2,axis=0)

array([[3, 4, 3, 6],
       [8, 6, 6, 4]], dtype=int32)

In [29]:
np.delete(arr4,(0,1),axis=1)
#delete column 0 and column 1from the array

array([[3, 6],
       [6, 4],
       [1, 8]], dtype=int32)

In [30]:
np.delete(arr4,(0,1,2),axis=0)

array([], shape=(0, 4), dtype=int32)

In [31]:
#creating copy of a array:
a=np.array([2,3,4,5])
b=np.copy(a)
b

array([2, 3, 4, 5])

In [33]:
#another method to copy:
b=a.copy()
b

array([2, 3, 4, 5])

SORTING:

In [34]:
a=[4,5,2,7,8]
np.sort(a)

array([2, 4, 5, 7, 8])

In [ ]:
np.sort(a)[::-1] # sort in descending 

array([8, 7, 5, 4, 2])

In [36]:
a.sort()
a

[2, 4, 5, 7, 8]

In [37]:
c=np.array([[3,2,3],[5,3,8],[5,3,0]])
c

array([[3, 2, 3],
       [5, 3, 8],
       [5, 3, 0]])

In [ ]:
np.sort(c) #sort in ascending

array([[2, 3, 3],
       [3, 5, 8],
       [0, 3, 5]])

In [40]:
np.sort(c)[::-1]

array([[0, 3, 5],
       [3, 5, 8],
       [2, 3, 3]])

In [41]:
c

array([[3, 2, 3],
       [5, 3, 8],
       [5, 3, 0]])

In [42]:
-c

array([[-3, -2, -3],
       [-5, -3, -8],
       [-5, -3,  0]])

In [43]:
np.sort(-c)

array([[-3, -3, -2],
       [-8, -5, -3],
       [-5, -3,  0]])

In [44]:
-np.sort(-c)

array([[3, 3, 2],
       [8, 5, 3],
       [5, 3, 0]])

In [45]:
-c
np.sort(-c)
-np.sort(-c)

array([[3, 3, 2],
       [8, 5, 3],
       [5, 3, 0]])

In [46]:
import numpy as np
arr=np.array([[12,5,7],[1,3,9],[8,2,6]])
print(arr)
s_arr=np.sort(arr,axis=1)
print(s_arr)
#axis 0=column(vertical)
#axis 1=row(horizonatl)

[[12  5  7]
 [ 1  3  9]
 [ 8  2  6]]
[[ 5  7 12]
 [ 1  3  9]
 [ 2  6  8]]


In [4]:
import numpy as np
arr1=np.random.randint(2,8,(3,3))
arr2=np.random.randint(0,5,(3,3))
arr3=np.random.randint(3,9,(3,3))
print(arr1)
print(arr2)
print(arr3)

[[6 6 2]
 [7 5 6]
 [4 5 4]]
[[0 4 2]
 [2 3 1]
 [2 4 3]]
[[5 6 4]
 [7 7 5]
 [4 4 5]]


In [ ]:
np.vstack([arr1,arr2,arr3])#verical stack

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4],
       [0, 4, 2],
       [2, 3, 1],
       [2, 4, 3],
       [5, 6, 4],
       [7, 7, 5],
       [4, 4, 5]], dtype=int32)

In [6]:
np.concatenate([arr1,arr2],axis=0)#same as v stack

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4],
       [0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [7]:
np.hstack([arr1,arr2])

array([[6, 6, 2, 0, 4, 2],
       [7, 5, 6, 2, 3, 1],
       [4, 5, 4, 2, 4, 3]], dtype=int32)

In [8]:
np.concatenate([arr1,arr2],axis=1)#same as hstack

array([[6, 6, 2, 0, 4, 2],
       [7, 5, 6, 2, 3, 1],
       [4, 5, 4, 2, 4, 3]], dtype=int32)

In [9]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [ ]:
arr1.ravel()#convert multidimnsional array into 1D

array([6, 6, 2, 7, 5, 6, 4, 5, 4], dtype=int32)

In [12]:
arr3

array([[5, 6, 4],
       [7, 7, 5],
       [4, 4, 5]], dtype=int32)

In [14]:
arr3[1,2]#accesing a particular elemnt ,1row,2nd column (zero index)

np.int32(5)

In [15]:
arr3[0::2,0:1]
#arr[row,column]
#arr[start:stop:step,start:stop:step]

array([[5],
       [4]], dtype=int32)

In [16]:
arr=np.array([[3,2,-1,4],[8,7,0,1],[2,6,3,-5],[4,8,7,2]])
arr

array([[ 3,  2, -1,  4],
       [ 8,  7,  0,  1],
       [ 2,  6,  3, -5],
       [ 4,  8,  7,  2]])

In [17]:
arr[1:3:,1::2]

array([[ 7,  1],
       [ 6, -5]])

In [18]:
arr[1::2,0:2:]

array([[8, 7],
       [4, 8]])

In [ ]:
#access elemnt diagonally
arr=np.array([[3,2,-1,4],[8,7,0,1],[2,6,3,-5],[4,8,7,2]])
arr

array([[ 3,  2, -1,  4],
       [ 8,  7,  0,  1],
       [ 2,  6,  3, -5],
       [ 4,  8,  7,  2]])

In [21]:
b=arr.diagonal()
b

array([3, 7, 3, 2])

In [30]:
ar=np.zeros((8,8))
ar

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
ar[::2,::2]=1
print(ar)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [32]:
ar[1::2,1::2]=1
print(ar)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


ARRAY ARITHEMETIC OPERATION:

In [33]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [34]:
arr2

array([[0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [ ]:
arr1*arr2 #element wise multiplication

array([[ 0, 24,  4],
       [14, 15,  6],
       [ 8, 20, 12]], dtype=int32)

In [36]:
np.matmul(arr1,arr2)#matrix multiplication

array([[16, 50, 24],
       [22, 67, 37],
       [18, 47, 25]], dtype=int32)

In [38]:
a=np.ones((2,3))
b=np.full((3,2),5)
c=np.full((2,3),5)
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[5 5 5]
 [5 5 5]]


In [39]:
np.matmul(a,b)

array([[15., 15.],
       [15., 15.]])

In [40]:
np.matmul(b,a)

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [41]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [42]:
np.max(arr1)

np.int32(7)

In [43]:
np.min(arr1)

np.int32(2)

In [44]:
np.max(arr1,axis=0)#column 

array([7, 6, 6], dtype=int32)

In [47]:
np.min(arr1,axis=0)

array([4, 5, 2], dtype=int32)

In [48]:
np.max(arr1,axis=1)#row

array([6, 7, 5], dtype=int32)

In [49]:
np.min(arr1,axis=1)

array([2, 5, 4], dtype=int32)

In [50]:
np.sum(arr1)

np.int64(45)

In [51]:
np.sum([arr1,arr2])

np.int64(66)

In [52]:
arr1

array([[6, 6, 2],
       [7, 5, 6],
       [4, 5, 4]], dtype=int32)

In [53]:
arr2

array([[0, 4, 2],
       [2, 3, 1],
       [2, 4, 3]], dtype=int32)

In [54]:
np.sum([arr1,arr2],axis=0)#column wisw adds

array([[ 6, 10,  4],
       [ 9,  8,  7],
       [ 6,  9,  7]])